### ISSUE TITLE
Fix for potential current_streak bug experienced in UTC−05:00

### ISSUE THREAD

**Issue by vxsl** [IonicaBizau/github-calendar-parser#18]
Using the `github-calendar` package from @Bloggify, I noticed that the `current_streak` property was incorrectly evaluating to 0. Taking a look at the `github-calendar-parser` code, I then noticed that the data from the current day was being considered in the calculation, which I am assuming is not the intended functionality.

In order to make the package functional for my purposes, [I made a revision](https://github.com/vxsl/github-calendar-parser/tree/current-streak-fix) that ignores data if the parsed date from the `<g transform...` element matches today's date. In order to ensure an accurate comparison of the two dates, the argument to the `Date` constructor in `obj.date` needed to be appended with `' 00:00'` as discussed [here](https://stackoverflow.com/questions/39223481/incorrect-date-shown-in-new-date-in-javascript). Otherwise, for example, `2021-01-22` results in a `Date` object for January 21, 2021 instead of January 22.

With the revision, my package now works perfectly in my timezone (UTC−05:00). I would imagine that the problem I am addressing is only present in certain timezones to begin with.

**Comment by vxsl** [comment]
> . In order to ensure an accurate comparison of the two dates, the argument to the Date constructor in obj.date needed to be appended with ' 00:00' as discussed here. Otherwise, for example, 2021-01-22 results in a Date object for January 21, 2021 instead of January 22.

Regarding this part of the issue, it is also worth noting that in my experience the current streak _range_ was also incorrect before applying the revision. Essentially, all parsed dates were one day earlier than they should have been.

**Comment by IonicaBizau** [comment]
Feel free to submit a pull request with the change. Thanks!
