### ISSUE TITLE
Requires an unecessary dependency

### ISSUE THREAD

**Issue by bdlowery** [IonicaBizau/github-calendar-parser#27]
Why on earth does this require a dependency that's just an array of colors?
```
const colorLegend = require("github-calendar-legend")
```

`github-calendar-legend` is literally 7 lines of code
```
module.exports = [
    "#eee"
  , "#d6e685"
  , "#8cc665"
  , "#44a340"
  , "#1e6823"
];
```
Not everything needs to be an npm package. Please make it make sense.

**Comment by IonicaBizau** [comment]
Sorry for the confusion, @bdlowery. The reasoning for this was that this array of colors is used by other packages too. And when GitHub changes the colors, it’s easy to update all the packages at once. 
Again, I see how this could be confusing and sorry for that.

Cheers!
